feature/SS-111
lunasoft/sw-tools-net pull request #10
Opened 2024-01-30 22:49 UTC by SebastianSW

- Se agrega función ReadPfx
- Se documenta función ReadPfx
- Se sube versión

2024-01-31 00:17 UTC, FerCarrilloM approved these changes

2024-01-31 00:33 UTC, ReyesSW approved these changes

2024-02-01 15:10 UTC, marifersw commented on test/SW-Tools-Net-UnitTest/Resources/Xml/ut_cce20.xml
> -        TipoCambioUSD= "17.1125" TotalUSD= "20.00">
Muestra un error de TipoCambioUSD, podria considerar omitirse la UT de este archivo para evitar el error.

2024-02-01 15:11 UTC, marifersw approved these changes

2024-02-01 15:29 UTC, SebastianSW commented on test/SW-Tools-Net-UnitTest/Resources/Xml/ut_cce20.xml
> -        TipoCambioUSD= "17.1125" TotalUSD= "20.00">
Se omite la UT para evitar errores a futuro.

2024-02-01 15:57 UTC, martinfnsw approved these changes

2024-02-02 19:56 UTC, SwAeyrton requested changes

2024-02-02 19:56 UTC, SwAeyrton commented on src/SW-Tools-Net/Entities/Response/CertificateResponse.cs
> +    public CertificateResponseData(byte[] publicCert, byte[] privateCert)
el metodo debe ser interno para el response no se pueda modificar externamente

2024-02-02 19:56 UTC, SwAeyrton commented on src/SW-Tools-Net/Entities/Response/CertificateResponse.cs
>  public class CertificateResponseData
sugiero crear  otro responseData para que no vengan propiedades nulas o vacias en la respuesta, quizas modififcar el response que existia por PfxResponseData y para el nuemo metodo sea CertificateResponseData

2024-02-02 19:56 UTC, SwAeyrton commented on src/SW-Tools-Net/Services/Certificate/Certificate.cs
> +        _handler = new CertificateServiceHandler();
la sintaxis era correcta, por que se modifica?

2024-02-02 19:56 UTC, SwAeyrton commented on src/SW-Tools-Net/Services/Certificate/Certificate.cs
> -        return _handler.Execute(() => CertificatePfxService(publicCertificate, privateKey, password));
por que se modifica?

2024-02-02 19:56 UTC, SwAeyrton commented on src/SW-Tools-Net/Services/Certificate/Certificate.cs
> +    {
toda esta logica ya existe en el handler, solo se debe ejecutar el metodo del service, asi como estaba en el metodo CreatePfx

2024-02-05 06:05 UTC, SebastianSW commented on src/SW-Tools-Net/Entities/Response/CertificateResponse.cs
> +    public CertificateResponseData(byte[] publicCert, byte[] privateCert)
Se realizó la mejora en el manejo de la respuesta.

2024-02-05 06:05 UTC, SebastianSW commented on src/SW-Tools-Net/Entities/Response/CertificateResponse.cs
>  public class CertificateResponseData
Se agrega PfxReponse para no afectar la lógica ya existente.

2024-02-05 06:06 UTC, SebastianSW commented on src/SW-Tools-Net/Services/Certificate/Certificate.cs
> +        _handler = new CertificateServiceHandler();
Se regresa codigo original, un error en autocomplete

2024-02-05 06:07 UTC, SebastianSW commented on src/SW-Tools-Net/Services/Certificate/Certificate.cs
> -        return _handler.Execute(() => CertificatePfxService(publicCertificate, privateKey, password));
Se regresa lógica existente para la ejecución de los métodos.

2024-02-05 06:08 UTC, SebastianSW commented on src/SW-Tools-Net/Services/Certificate/Certificate.cs
> +    {
Se eliminó codigo innecesario para la ejecución del proceso.

2024-02-08 21:48 UTC, SwAeyrton approved these changes

2024-02-08 22:22 UTC, merged