Recursos para C.P 3.1
lunasoft/sw-tools-net pull request #11
Opened 2024-07-19 18:58 UTC by NayeliRamirezL

2024-07-19 19:16 UTC, ReyesSW approved these changes

2024-07-19 19:21 UTC, SebastianSW approved these changes

2024-07-22 16:10 UTC, FerCarrilloM requested changes

2024-07-22 16:10 UTC, FerCarrilloM commented on test/SW-Tools-Net-UnitTest/SignTest.cs
> +        [Fact(Skip = "Carta Porte 3.0 no vigente")]
Veo que salta la UT de Carta Porte 3.1, pero me parece que hace falta la UT de Carta porte 3.1

2024-07-22 16:36 UTC, FerCarrilloM approved these changes

2024-07-22 16:36 UTC, FerCarrilloM commented on test/SW-Tools-Net-UnitTest/Resources/Xml/ut_cp31.xml
> +	<cfdi:Emisor Rfc="EKU9003173C9" RegimenFiscal="601" Nombre="ESCUELA KEMPER URGATE" />
Me parece que en esta Librería se usan los ejemplos con el RFC   H&E951128469.

2024-07-23 15:59 UTC, marifersw approved these changes

2024-07-23 16:15 UTC, merged