Feature/ss429
lunasoft/sw-tools-net pull request #4
Opened 2023-11-24 17:51 UTC by FerCarrilloM

2023-11-24 18:48 UTC, SebastianSW approved these changes

2023-11-24 22:07 UTC, SwAeyrton requested changes

2023-11-24 22:07 UTC, SwAeyrton commented on test/SW-Tools-Net-UnitTest/CertificateTest.cs
> +        private readonly byte[] _BytesCer;
![image](https://github.com/lunasoft/sw-tools-net/assets/88451104/19fcf1f5-15de-4091-8d29-7ef32bef5a4f)

2023-11-24 22:07 UTC, SwAeyrton commented on src/SW-Tools-Net/Helpers/CertificateUtils.cs
> +        public static RSACryptoServiceProvider ToRSA(RsaPrivateCrtKeyParameters privKey)
Si solo se usa dentro del ensamblado, podria quedar como internal

2023-11-24 22:07 UTC, SwAeyrton commented on src/SW-Tools-Net/SW.Tools.csproj
> +    <PackageReference Include="BouncyCastle.Cryptography" Version="2.2.1" />
Sugiero encarecidamente usar chilkat en lugar de bouncycastle, se puede tomar como ejemeplo https://bitbucket.org/smarterweb/smarter-tooling/src/develop/src/Application/Smarter.Tooling.Application/Services/FunctionServices/CreatePfx.cs

2023-11-24 22:07 UTC, SwAeyrton commented on src/SW-Tools-Net/Services/Certificate/Certificate.cs
> +    public CertificateResponse CreatePfx(byte[] bytesCER, byte[] bytesKEY, string password)
el nombre de los parametros sugiero sean mas descriptivos, el tipo de dato ya sugiere que son bytes, se puede usar el mismo nombra de la Interfaz o un similar.

2023-11-24 22:07 UTC, SwAeyrton commented on README.md
> +byte[] BytesCer = File.ReadAllBytes("h&e951128469.cer");
camelCase

2023-11-24 22:07 UTC, SwAeyrton commented on test/SW-Tools-Net-UnitTest/CertificateTest.cs
> +            Assert.True(result.Status == "error");
Sugiero utilizar los CustomAssert que estan en Helpers para validar los response de las UT de success y error

2023-11-27 17:42 UTC, ReyesSW approved these changes

2023-11-27 17:58 UTC, SwAeyrton approved these changes

2023-11-27 19:14 UTC, martinfnsw approved these changes

2023-11-27 19:21 UTC, merged