Update Sign Service
lunasoft/sw-tools-net pull request #5
Opened 2023-12-08 17:06 UTC by martinfnsw

Se agregan clases para firmado de xml

2023-12-08 17:24 UTC, ReyesSW commented on test/SW-Tools-Net-UnitTest/SignXmlTest.cs
> +        public void SignedXml_Cancelattion_Succes()
Un error gramatico Cancelattion

2023-12-08 17:29 UTC, ReyesSW reviewed
Deje unos comentarios en las UT

2023-12-08 17:29 UTC, ReyesSW commented on test/SW-Tools-Net-UnitTest/SignXmlTest.cs
> +        public void Sign_Cancelattion_Succes()
Sign_Cancelattion_Succes y SignedXml_Cancelattion_Succes creo que realizan la misma prueba.

2023-12-08 20:55 UTC, marifersw approved these changes

2023-12-11 14:58 UTC, SebastianSW approved these changes

2023-12-11 15:51 UTC, SwAeyrton requested changes

2023-12-11 15:51 UTC, SwAeyrton commented on src/SW-Tools-Net/Helpers/CryptoHelper.cs
> +        System.Text.StringBuilder sb = new();
El namespace system.text ya esta agregado arriba, seria dejar esas o esta.

2023-12-11 15:51 UTC, SwAeyrton commented on src/SW-Tools-Net/Helpers/CryptoHelper.cs
> +        new Global().UnlockBundle("LUNASF.CB1122019_6AkG5xXC37m0");
Esto no deberia estar aqui, es codigo privado, si es requerido el unlock code, entonces mejor cambiar la forma de hacerlo

2023-12-11 21:45 UTC, martinfnsw commented on src/SW-Tools-Net/Helpers/CryptoHelper.cs
> +        System.Text.StringBuilder sb = new();
Si se deja solo el namespace genera ambiguedad con chilkat
![ambiguedad](https://github.com/lunasoft/sw-tools-net/assets/88680430/2a5f5b5e-1a17-4bad-9d7c-7b42c486ef2d)

por lo que se deja en la misma línea

2023-12-11 22:17 UTC, martinfnsw commented on src/SW-Tools-Net/Helpers/CryptoHelper.cs
> +        new Global().UnlockBundle("LUNASF.CB1122019_6AkG5xXC37m0");
Se agrega como variable de entorno

2023-12-12 08:08 UTC, SwAeyrton requested changes

2023-12-12 08:08 UTC, SwAeyrton commented on test/SW-Tools-Net-UnitTest/Helpers/CustomAssert.cs
> +        _acceptReject = new (BuildTest.UrlService, BuildTest.Token);
crear estas instancias solo en la UT correspondiente, crearlas no se ve muy conveniente, ya que se estarian creando en todas las UT y no en todas se usan

2023-12-12 08:08 UTC, SwAeyrton commented on src/SW-Tools-Net/Validations/ValidationSign.cs
> +        if (!isRetention && (tag != "cfdi:Comprobante" && tag != "Cancelacion" && tag != "SolicitudAceptacionRechazo"))
Si se modifica este metodo, ya no es necesario el uso del booleano isRetention

2023-12-12 23:47 UTC, SwAeyrton requested changes

2023-12-12 23:47 UTC, SwAeyrton commented on src/SW-Tools-Net/Validations/ValidationSign.cs
> +        catch (Exception ex)
este catch no tiene mucho sentido porque arriba estas lanzando un ArgumentException pero da igual el tipo de excepcion que mandes siempre van a caer aqui y siempre se va a mandar el mensaje que contiene la excepcion que se lanza en el catch, solo es lanzar el throw new ArgumentException de arriba y omitir este try catch

2023-12-13 15:29 UTC, SwAeyrton approved these changes

2023-12-13 17:09 UTC, merged